#!/bin/sh

out=$(echo '{ "command": ["get_property", "pause"]}' | socat - /tmp/mpvsocket 2>/dev/null)
case $1 in
	song)
		if [ -n "$out" ] && pgrep -f mpvsocket >/dev/null 2>&1;then
			cut -d'>' -f1 < "$HOME/.cache/yt-music/current" | cut -d':' -f2 | sed 's|[^-]*$||;s|-$||'
		else
			echo "Offline"
		fi
		;;
	artist)
		if [ -n "$out" ] && pgrep -f mpvsocket >/dev/null 2>&1;then
			cut -d'>' -f1 < "$HOME/.cache/yt-music/current" | sed 's_.* -__'
		else
			echo "Offline"
		fi
		;;
	cover)
		if [ -n "$out" ] && pgrep -f mpvsocket >/dev/null 2>&1;then
			echo "$HOME/.cache/yt-music/default.jpg"
		else
			echo "$HOME/.config/eww/music.png"
		fi
		;;
	status)
		if [ -z "$out" ];then
			printf ""
		elif printf "%s" "$out" | grep -q "true";then
			echo "喇"
		else
			echo ""
		fi
		;;
	play_toggle)
		echo cycle pause | socat - "/tmp/mpvsocket"
		;;
	next)
		pgrep -f mpvsocket >/dev/null 2>&1 && /home/tanveer/repos_scripts/yt-music play_next
		;;
	prev)
		pgrep -f mpvsocket >/dev/null 2>&1 && ($HOME/repos_scripts/yt-music play "$(sed 's| >|\t|g' $HOME/.cache/yt-music/prev | cut -d':' -f2)")
		;;
	time)
		out=$(echo '{"command" :["get_property" , "percent-pos"]}' | socat - /tmp/mpvsocket 2>/dev/null | sed -nE 's_.*data":([^,]*).*_\1_p')
		[ -z "$out" ] && echo "100" || echo "$out"
		;;
	seek)
		echo "{\"command\" :[\"seek\" ,\"$2\",\"relative-percent\"]}" | socat - /tmp/mpvsocket
		;;
esac
