#!/bin/sh

#script for bookmarking selected items and later using it..

data="$(wl-paste -p | tr '\n' '\`' | sed 's/$/ /g')"

file="$HOME/.cache/bookmarks"
oshi_file="$HOME/.cache/oshi-urls"

case $1 in 
	add)
    		if [ -z "$data" ];then
    		   	 notify-send "Please select anything to bookmark"
    		elif grep -q "${data}" "$file";then
    		   	 notify-send -i "bookmark-missing" "Already bookmarked"
    		else
    		   	 printf "%s" "$data" >> "$file"
    		   	 notify-send -i "user-bookmarks" "Bookmarked" "$data"
    		fi
		;;
	rm)
    		data="$(sed '/^$/d' "$file" | nl -n'ln')"
    		[ -z "$data" ] && notify-send "Bookmark is empty" && exit 0
    		del=$(printf "%s" "$data" | bemenu --fn 'Roboto 15' -i -c -W 0.6 -B 3 -l 30 -p "delete-bookmark :" | cut -f1)
    		[ -z "$del" ] || (sed -i "${del}d" "$file" && notify-send -i "bookmark-missing" "Bookmark deleted" -u critical)
		;;
	copy)
		sed '/^$/d' "$file" "$oshi_file" | sed -E 's/.*DL: ([^|]*).*/\1/g' | bemenu --fn 'Roboto 15' -i -c -W 0.6 -B 3 -l 30 -p "Put-bookmark :" | tr '\`' '\n' | wl-copy && notify-send "Copied to clipboard" -i "com.github.davidmhewitt.clipped"
		;;
	*)
		wtype -d 10 "$(sed '/^$/d' "$file" "$oshi_file" | sed -E 's/.*DL: ([^|]*).*/\1/g' | bemenu --fn 'Roboto 15' -i -c -W 0.6 -B 3 -l 30 -p "Put-bookmark :" | tr '\`' '\n')"
		;;
esac

sed -i '/^$/d' "$file"
printf "\n" >> "$file"
