#!/bin/sh

i=5
while [ $i -gt 0 ]; do
	notify-send -e -i "/usr/share/icons/Papirus/16x16/panel/clockify-blue.svg" "$(date)" -h "string:x-canonical-private-synchronous:${0##*/}" -t 1200 &
	sleep 1
	: $((i -= 1))
done
