#!/bin/sh

menu() {
	bemenu --fn 'IBM Plex Sans 15' -i -c -W "0.${2:-5}" -B 3 -p "$1" -l 25 -P ">>"
}

[ -z "$1" ] && dir="$HOME/repos_scripts" || dir="$1"

[ -d "$dir" ] || exit 0

script=$(find "$dir" -maxdepth 1 -type f ! -name '*.md' ! -name ".*" -printf "%f\n" | menu "Run Script: " "2")

[ -z "$script" ] && exit 0

sh -c "$dir/$script"
