#!/bin/sh

$HOME/.config/hypr/workspace &
case "$(printf "lock\\nsuspend\\nlogout\\nreboot\\npoweroff" | bemenu --fn 'Roboto 15' -i -c -W 0.6 -B 3 -l 5 -p "⏻ " -H 40)" in
	#lock) $HOME/.config/bspwm/screenlock.sh ;;
	suspend) systemctl suspend ;;
	logout) systemctl logout ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
