#!/bin/sh

vol_int=$(pamixer --get-volume)
vol_icon="low"
[ "$vol_int" -gt 0 ] && pamixer -u || pamixer -m
[ "$vol_int" -gt 33 ] && vol_icon="medium"
[ "$vol_int" -gt 66 ] && vol_icon="high"
pamixer --get-mute | sh && vol_icon="muted"
notify-send -i "/usr/share/icons/Papirus/16x16/panel/audio-volume-$vol_icon.svg" "$vol_int %" -h "string:x-canonical-private-synchronous:volume" -t 1000
