#!/bin/bash
if nmcli radio wifi | grep -q 'enabled'; then
	nmcli radio wifi off
	wifi_icon="offline"
else
	nmcli radio wifi on
	wifi_icon="acquiring"
fi
notify-send -e -i "/usr/share/icons/Papirus/16x16/panel/network-wireless-$wifi_icon.svg" "wifi $(nmcli radio wifi)" -h "string:x-canonical-private-synchronous:${0##*/}"
