#source user-defined functions
source "${${(%):-%x}:A:h}/functions"

# EXPORTS
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export TZ="Asia/Kolkata"
export PODMAN_COMPOSE_WARNING_LOGS=false
export PATH="$PATH:$HOME/scripts:$HOME/.local/bin"

# XDG SPECS
export XDG_DOWNLOAD_DIR="$HOME/dls"
export XDG_DOCUMENTS_DIR="$HOME/docs"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pics"
export XDG_VIDEOS_DIR="$HOME/vids"

# ALIASES
alias cat="bat -pp --color=always"
alias open="xdg-open"
alias cp="cp -v"
alias lsblk="lsblk -o 'NAME,SIZE,FSAVAIL,FSUSED,FSUSE%,FSTYPE,MOUNTPOINTS'"
alias art="php artisan"
alias rm="rm -v"
alias mv="mv -v"
alias pgrep="pgrep -af"
alias grep="grep --color=auto"
alias ncdu="ncdu --color dark"
alias ll="lsd --color=auto -alh"
alias ls="lsd --color=auto"
alias nchh="nvim ~/.config/hypr/hyprland.conf"
alias shfmt="shfmt -ci -d -w"
alias reboot_firmware="systemctl reboot --firmware-setup"
alias sail="./vendor/bin/sail"

#config
HISTFILE=$HOME/.histfile
HISTSIZE=500
SAVEHIST=500
clshist
PROMPT_EOL_MARK=' ⏎ '
setopt autocd
bindkey -e
zstyle :compinstall filename "$0"
fpath=($HOME/.config/zsh/completions $fpath)
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
eval "$(starship init zsh)"

#plugins
[ -f "/usr/share/nvm/init-nvm.sh" ] && source /usr/share/nvm/init-nvm.sh
[ -f "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ] && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ] && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f "/usr/share/zsh/plugins/fzf-tab-git/fzf-tab.zsh" ] && source /usr/share/zsh/plugins/fzf-tab-git/fzf-tab.zsh
